version: '3.8'

services:
  db:
    image: mongo
    restart: always
    volumes:
      - "dbdata:/data/db"
    container_name: db
    env_file:
      - ./.env
    ports:
      - '27017:27017'

  bot:
    build:
      context: ../recruiter_bot/
      dockerfile: Dockerfile
    depends_on:
      - db
    restart: always
    env_file:
      - ./.env

volumes:
  dbdata: